name: store_core
description: A new Flutter package project.
version: 0.0.3
homepage: https://github.com/RamiDmour/store_features
publish_to: https://dart.pkg.jetbrains.space/dartpubtest/p/main/storefeatures/

environment:
  sdk: ">=3.1.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.1.1
  dio: ^5.4.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7

flutter:
